In [6]:
# =========================
# 1. IMPORT LIBRARIES
# =========================
import pandas as pd
import numpy as np

# =========================
# 2. LOAD DATASET
# =========================
df = pd.read_csv("credit_card_customers.csv")  # your dataset

print(df.shape)
df.head()

(8000, 7)

   age  income  transactions  credit_limit  avg_spent  payment_delay  churn
0   56  147595            33         16378       2489             28      1
1   69   31549            78         11864       9220             22      0
2   46   91216            17         19803       3104             10      1
3   32   45739            57          5279       2907             15      0
4   60   41209            83         18057        563             16      0

In [3]:
import numpy as np
import pandas as pd

np.random.seed(42)

df = pd.DataFrame({
    "age": np.random.randint(18, 70, 8000),
    "income": np.random.randint(20000, 150000, 8000),
    "transactions": np.random.randint(1, 100, 8000),
    "credit_limit": np.random.randint(1000, 20000, 8000),
    "avg_spent": np.random.randint(500, 10000, 8000),
    "payment_delay": np.random.randint(0, 30, 8000),
    "churn": np.random.randint(0, 2, 8000)
})

df.to_csv("credit_card_customers.csv", index=False)

df.head()

   age  income  transactions  credit_limit  avg_spent  payment_delay  churn
0   56  147595            33         16378       2489             28      1
1   69   31549            78         11864       9220             22      0
2   46   91216            17         19803       3104             10      1
3   32   45739            57          5279       2907             15      0
4   60   41209            83         18057        563             16      0

In [4]:
import os
print(os.getcwd())

C:\Users\HP\Desktop\CUSTOMER SEGMENTATION + CHURN PREDICTION

In [5]:
df = pd.read_csv("credit_card_customers.csv")
df.head()

   age  income  transactions  credit_limit  avg_spent  payment_delay  churn
0   56  147595            33         16378       2489             28      1
1   69   31549            78         11864       9220             22      0
2   46   91216            17         19803       3104             10      1
3   32   45739            57          5279       2907             15      0
4   60   41209            83         18057        563             16      0

In [7]:
# =========================
# 3. BASIC CLEANING
# =========================

# remove duplicates
df.drop_duplicates(inplace=True)

# missing values check
print(df.isnull().sum())

# fill missing values
df.fillna(df.median(numeric_only=True), inplace=True)

# categorical handling
df = pd.get_dummies(df, drop_first=True)

df.head()

age              0
income           0
transactions     0
credit_limit     0
avg_spent        0
payment_delay    0
churn            0
dtype: int64

   age  income  transactions  credit_limit  avg_spent  payment_delay  churn
0   56  147595            33         16378       2489             28      1
1   69   31549            78         11864       9220             22      0
2   46   91216            17         19803       3104             10      1
3   32   45739            57          5279       2907             15      0
4   60   41209            83         18057        563             16      0

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

df_scaled = pd.DataFrame(scaled_data, columns=df.columns)